"""
train_gnn.py
P09 — Access Control Anomaly Detection Agent

Full training pipeline for the GNN anomaly detector.
  - Loads training and test event streams (generated by train_tpp.py)
  - Builds user-door access graph
  - Trains GNNAnomalyDetector for up to 40 epochs
  - Evaluates: AUC-ROC, AUC-PR, Best F1
  - Saves trained model to models/gnn.pt
  - Saves evaluation plots to models/gnn_eval.png

Usage:
    python src/train_gnn.py
"""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__)))

import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from pathlib import Path
from sklearn.metrics import (
    roc_auc_score, average_precision_score,
    f1_score, precision_score, recall_score,
    roc_curve, precision_recall_curve,
)

from simulate_events import generate_event_stream, default_building
from gnn_model import AccessGraph, GNNAnomalyDetector, GNNTrainer, SEED

# ── Config ────────────────────────────────────────────────────────────────────

TRAIN_DAYS    = 30
TEST_DAYS     = 7
TRAIN_SEED    = 42
TEST_SEED     = 99
TRAIN_ANOMALY = 0.05
TEST_ANOMALY  = 0.20

N_EPOCHS      = 30
LR            = 1e-3
BATCH_SIZE    = 256
PATIENCE      = 999   # no early stopping — run all epochs

MODEL_PATH    = "models/gnn.pt"
PLOT_PATH     = "models/gnn_eval.png"
RESULTS_PATH  = "models/gnn_results.txt"
DEVICE        = "cpu"

# ── Helpers ───────────────────────────────────────────────────────────────────

def print_section(title: str):
    print("\n" + "=" * 60)
    print(f"  {title}")
    print("=" * 60)


def evaluate(trainer: GNNTrainer,
             test_df: pd.DataFrame,
             graph: AccessGraph):
    """Score test events and compute metrics at event level."""
    scored = trainer.score_events(test_df, graph)

    scores = scored["gnn_z_score"].values
    labels = scored["is_anomaly"].astype(int).values
    scores = np.nan_to_num(scores, nan=0.0)

    auc_roc = roc_auc_score(labels, scores) if labels.sum() > 0 else 0.0
    auc_pr  = average_precision_score(labels, scores) if labels.sum() > 0 else 0.0

    prec_arr, rec_arr, thr_arr = precision_recall_curve(labels, scores)
    f1s     = 2 * prec_arr * rec_arr / np.maximum(prec_arr + rec_arr, 1e-8)
    best_idx= np.argmax(f1s)
    best_f1 = f1s[best_idx]
    best_thr= thr_arr[best_idx] if best_idx < len(thr_arr) else trainer.threshold
    best_p  = prec_arr[best_idx]
    best_r  = rec_arr[best_idx]

    preds   = (scores >= trainer.threshold).astype(int)
    f1_t    = f1_score(labels, preds, zero_division=0)
    prec_t  = precision_score(labels, preds, zero_division=0)
    rec_t   = recall_score(labels, preds, zero_division=0)
    fpr_t   = (((preds == 1) & (labels == 0)).sum() /
               max((labels == 0).sum(), 1))

    metrics = dict(
        auc_roc=auc_roc, auc_pr=auc_pr,
        best_f1=best_f1, best_thresh=best_thr,
        best_precision=best_p, best_recall=best_r,
        f1_at_thresh=f1_t, prec_at_thresh=prec_t,
        rec_at_thresh=rec_t, fpr_at_thresh=fpr_t,
        n_total=len(labels),
        n_anomaly=int(labels.sum()),
        n_normal=int((labels == 0).sum()),
        random_baseline_pr=labels.mean(),
        threshold=trainer.threshold,
    )
    return scores, labels, metrics


def plot_results(scores, labels, metrics, losses, trainer, save_path):
    fig = plt.figure(figsize=(16, 12))
    fig.suptitle("P09 — GNN Anomaly Detection Evaluation",
                 fontsize=14, fontweight="bold")
    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.35, wspace=0.3)

    normal_scores  = scores[labels == 0]
    anomaly_scores = scores[labels == 1]

    # Training loss
    ax1 = fig.add_subplot(gs[0, 0])
    ax1.plot(range(1, len(losses)+1), losses,
             color="#2196F3", linewidth=2, marker="o", markersize=3)
    ax1.axhline(losses[-1], color="gray", linestyle="--",
                label=f"Final MSE: {losses[-1]:.6f}")
    ax1.set_xlabel("Epoch")
    ax1.set_ylabel("MSE Loss")
    ax1.set_title("GNN Training Loss Curve")
    ax1.legend(fontsize=9)
    ax1.grid(True, alpha=0.3)

    # Score distribution
    ax2 = fig.add_subplot(gs[0, 1])
    clip_val = np.percentile(scores, 99)
    bins = np.linspace(scores.min(), clip_val, 50)
    ax2.hist(normal_scores.clip(max=clip_val), bins=bins,
             alpha=0.6, color="#2196F3",
             label=f"Normal (n={len(normal_scores)})", density=True)
    ax2.hist(anomaly_scores.clip(max=clip_val), bins=bins,
             alpha=0.6, color="#F44336",
             label=f"Anomalous (n={len(anomaly_scores)})", density=True)
    ax2.axvline(trainer.threshold, color="black", linestyle="--",
                linewidth=1.5,
                label=f"Threshold={trainer.threshold:.2f}")
    ax2.set_xlabel("GNN Anomaly Score (Z-score)")
    ax2.set_ylabel("Density")
    ax2.set_title("Score Distribution — Test Set")
    ax2.legend(fontsize=9)
    ax2.grid(True, alpha=0.3)

    # ROC curve
    ax3 = fig.add_subplot(gs[1, 0])
    fpr, tpr, _ = roc_curve(labels, scores)
    ax3.plot(fpr, tpr, color="#F44336", linewidth=2,
             label=f"GNN (AUC={metrics['auc_roc']:.3f})")
    ax3.plot([0,1],[0,1], "k--", linewidth=1, label="Random (0.500)")
    ax3.set_xlabel("False Positive Rate")
    ax3.set_ylabel("True Positive Rate")
    ax3.set_title("ROC Curve")
    ax3.legend(fontsize=9)
    ax3.grid(True, alpha=0.3)

    # PR curve
    ax4 = fig.add_subplot(gs[1, 1])
    prec, rec, _ = precision_recall_curve(labels, scores)
    ax4.plot(rec, prec, color="#4CAF50", linewidth=2,
             label=f"GNN (AUC-PR={metrics['auc_pr']:.3f})")
    ax4.axhline(metrics["random_baseline_pr"], color="gray",
                linestyle="--",
                label=f"Random ({metrics['random_baseline_pr']:.3f})")
    ax4.set_xlabel("Recall")
    ax4.set_ylabel("Precision")
    ax4.set_title("Precision-Recall Curve")
    ax4.legend(fontsize=9)
    ax4.grid(True, alpha=0.3)

    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Plot saved to {save_path}")


def save_results(metrics, losses, save_path):
    with open(save_path, "w") as f:
        f.write("=" * 60 + "\n")
        f.write("P09 — GNN Evaluation Results\n")
        f.write("=" * 60 + "\n\n")
        f.write(f"Test events:       {metrics['n_total']:,}\n")
        f.write(f"  Normal:          {metrics['n_normal']:,}\n")
        f.write(f"  Anomalous:       {metrics['n_anomaly']:,}\n")
        f.write(f"  Random AUC-PR:   {metrics['random_baseline_pr']:.3f}\n\n")
        f.write(f"AUC-ROC:           {metrics['auc_roc']:.4f}\n")
        f.write(f"AUC-PR:            {metrics['auc_pr']:.4f}\n")
        f.write(f"Best F1:           {metrics['best_f1']:.4f}\n")
        f.write(f"  Precision:       {metrics['best_precision']:.4f}\n")
        f.write(f"  Recall:          {metrics['best_recall']:.4f}\n")
        f.write(f"  At threshold:    {metrics['best_thresh']:.4f}\n\n")
        f.write(f"At 95th pct threshold ({metrics['threshold']:.4f}):\n")
        f.write(f"  F1:              {metrics['f1_at_thresh']:.4f}\n")
        f.write(f"  Precision:       {metrics['prec_at_thresh']:.4f}\n")
        f.write(f"  Recall:          {metrics['rec_at_thresh']:.4f}\n")
        f.write(f"  FPR:             {metrics['fpr_at_thresh']:.4f}\n\n")
        f.write(f"Training:\n")
        f.write(f"  Epochs:          {len(losses)}\n")
        f.write(f"  Final MSE:       {losses[-1]:.6f}\n")
    print(f"Results saved to {save_path}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    torch.manual_seed(SEED)
    np.random.seed(SEED)
    Path("models").mkdir(exist_ok=True)

    # ── Step 1: Load or generate data ────────────────────────────────────────
    print_section("STEP 1: Loading event streams")

    train_path = "data/processed/train_events.csv"
    test_path  = "data/processed/test_events.csv"

    print("Generating event streams...")
    building_train = default_building()
    building_train.anomaly_rate = TRAIN_ANOMALY
    train_df = generate_event_stream(
        n_days=TRAIN_DAYS, seed=TRAIN_SEED, building=building_train)

    building_test = default_building()
    building_test.anomaly_rate = TEST_ANOMALY
    test_df = generate_event_stream(
        n_days=TEST_DAYS, seed=TEST_SEED, building=building_test)

    print(f"Train events: {len(train_df):,}  "
          f"(anomalous: {train_df['is_anomaly'].sum()})")
    print(f"Test events:  {len(test_df):,}  "
          f"(anomalous: {test_df['is_anomaly'].sum()})")

    # ── Step 2: Build access graph ────────────────────────────────────────────
    print_section("STEP 2: Building access graph")

    graph = AccessGraph()
    graph.fit(train_df)
    print(f"Users : {graph.n_users}")
    print(f"Doors : {graph.n_doors}")
    print(f"Nodes : {graph.n_nodes}")

    # ── Step 3: Initialise model ──────────────────────────────────────────────
    print_section("STEP 3: Initialising GNN model")

    model   = GNNAnomalyDetector()
    trainer = GNNTrainer(model, device=DEVICE)
    n_params = sum(p.numel() for p in model.parameters()
                   if p.requires_grad)
    print(f"Parameters : {n_params:,}")
    print(f"Device     : {DEVICE}")

    # ── Step 4: Train ─────────────────────────────────────────────────────────
    print_section("STEP 4: Training GNN (40 epochs)")

    losses = trainer.fit(
        train_df, graph,
        n_epochs=N_EPOCHS,
        lr=LR,
        batch_size=BATCH_SIZE,
        patience=PATIENCE,
    )

    # ── Step 5: Evaluate ──────────────────────────────────────────────────────
    print_section("STEP 5: Evaluating on test set")

    scores, labels, metrics = evaluate(trainer, test_df, graph)

    print(f"\nTest events : {metrics['n_total']:,} "
          f"({metrics['n_anomaly']} anomalous, "
          f"{metrics['n_normal']} normal)")
    print(f"Random AUC-PR baseline: {metrics['random_baseline_pr']:.3f}")
    print(f"\n{'─'*40}")
    print(f"AUC-ROC  : {metrics['auc_roc']:.4f}")
    print(f"AUC-PR   : {metrics['auc_pr']:.4f}")
    print(f"Best F1  : {metrics['best_f1']:.4f}  "
          f"(Prec={metrics['best_precision']:.3f}, "
          f"Rec={metrics['best_recall']:.3f})")
    print(f"{'─'*40}")
    print(f"At 95th pct threshold ({trainer.threshold:.4f}):")
    print(f"  F1        : {metrics['f1_at_thresh']:.4f}")
    print(f"  Precision : {metrics['prec_at_thresh']:.4f}")
    print(f"  Recall    : {metrics['rec_at_thresh']:.4f}")
    print(f"  FPR       : {metrics['fpr_at_thresh']:.4f}")

    # ── Step 6: Save ──────────────────────────────────────────────────────────
    print_section("STEP 6: Saving model and results")

    trainer.save(MODEL_PATH, graph)
    plot_results(scores, labels, metrics, losses, trainer, PLOT_PATH)
    save_results(metrics, losses, RESULTS_PATH)

    print(f"\n{'='*60}")
    print(f"  GNN TRAINING COMPLETE")
    print(f"{'='*60}")
    print(f"  Model   : {MODEL_PATH}")
    print(f"  Plot    : {PLOT_PATH}")
    print(f"  Results : {RESULTS_PATH}")
    print(f"  AUC-ROC : {metrics['auc_roc']:.4f}")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()